# Generated by Django 3.2.6 on 2021-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0003_alter_generalinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(blank=True, help_text='ddd', max_length=50),
        ),
    ]
