# Generated by Django 3.2.6 on 2021-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0004_alter_generalinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ddf'),
        ),
    ]
