# Generated by Django 3.2.6 on 2021-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0005_alter_generalinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfBirth',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NaN'), (1, 'Andijan region'), (2, 'Bukhara region'), (3, 'Jizzakh region'), (4, 'Kashkadarya region'), (5, 'Navoi region'), (6, 'Namangan region'), (7, 'Samarkand region'), (8, 'Surkhandarya region'), (9, 'Syrdarya region'), (10, 'Tashkent region'), (11, 'Tashkent city'), (12, 'Fergana region'), (13, 'Khorezm region'), (14, 'Republic of Karakalpakstan')], default=0, verbose_name='Place Of Birth'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfResidence',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NaN'), (1, 'Andijan region'), (2, 'Bukhara region'), (3, 'Jizzakh region'), (4, 'Kashkadarya region'), (5, 'Navoi region'), (6, 'Namangan region'), (7, 'Samarkand region'), (8, 'Surkhandarya region'), (9, 'Syrdarya region'), (10, 'Tashkent region'), (11, 'Tashkent city'), (12, 'Fergana region'), (13, 'Khorezm region'), (14, 'Republic of Karakalpakstan')], default=0, verbose_name='Place Of Residence'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Surname'),
        ),
    ]
