# Generated by Django 3.2.6 on 2021-09-03 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0006_auto_20210902_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='age',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(75)], verbose_name='Age'),
        ),
    ]
