# Generated by Django 3.2.6 on 2021-09-03 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0009_auto_20210903_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(75)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='favTeams',
            field=models.CharField(choices=[('MU', 'Manchester United'), ('MCI', 'Manchester City'), ('CHEL', 'Chelsea'), ('LIV', 'Liverpool'), ('ARS', 'Arsenal'), ('TOT', 'Tottenham'), ('BAY', 'Bayern Munich'), ('BVB', 'Borussia Dortmund'), ('RM', 'Real Madrid'), ('BAR', 'Barcelona'), ('ATM', 'Atletico Madrid'), ('JUV', 'Juventus'), ('INT', 'Inter'), ('ROMA', 'Roma'), ('NAP', 'Napoli'), ('ACM', 'Milan'), ('PSG', 'Paris Saint-Germain'), ('OL', 'Olympique Lyonnais'), ('LIL', 'Lille')], max_length=50, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='favTeamsLeague',
            field=models.CharField(choices=[('EPL', 'Premier League - England'), ('BUN', 'Bundesliga - Germany'), ('La L', 'La Liga - Spain'), ('Seria A', 'Serie A - Italy'), ('L1', 'Ligue 1 - France')], max_length=50, verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfBirth',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NaN'), (1, 'Andijan region'), (2, 'Bukhara region'), (3, 'Jizzakh region'), (4, 'Kashkadarya region'), (5, 'Navoi region'), (6, 'Namangan region'), (7, 'Samarkand region'), (8, 'Surkhandarya region'), (9, 'Syrdarya region'), (10, 'Tashkent region'), (11, 'Tashkent city'), (12, 'Fergana region'), (13, 'Khorezm region'), (14, 'Republic of Karakalpakstan')], verbose_name='Place Of Birth'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfResidence',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NaN'), (1, 'Andijan region'), (2, 'Bukhara region'), (3, 'Jizzakh region'), (4, 'Kashkadarya region'), (5, 'Navoi region'), (6, 'Namangan region'), (7, 'Samarkand region'), (8, 'Surkhandarya region'), (9, 'Syrdarya region'), (10, 'Tashkent region'), (11, 'Tashkent city'), (12, 'Fergana region'), (13, 'Khorezm region'), (14, 'Republic of Karakalpakstan')], verbose_name='Place Of Residence'),
        ),
    ]
