# Generated by Django 3.2.6 on 2021-09-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0011_auto_20210903_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
