# Generated by Django 3.2.6 on 2021-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_favoriteTeams', '0015_auto_20210905_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfBirth',
            field=models.PositiveSmallIntegerField(choices=[('', ''), (1, 'Andijon viloyati'), (2, 'Buxoro viloyati'), (3, 'Jizzax viloyati'), (4, 'Qashqadaryo viloyati'), (5, 'Navoiy viloyati'), (6, 'Namangan viloyati'), (7, 'Samarqand viloyati'), (8, 'Surxondaryo viloyati'), (9, 'Sirdaryo viloyati'), (10, 'Toshkent viloyati'), (11, 'Fargʻona viloyati'), (12, 'Xorazm viloyati'), (13, 'Qoraqalpogʻiston Respublikasi')], verbose_name="Tug'ilgan Joyi*"),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='placeOfResidence',
            field=models.PositiveSmallIntegerField(choices=[('', ''), (1, 'Andijon viloyati'), (2, 'Buxoro viloyati'), (3, 'Jizzax viloyati'), (4, 'Qashqadaryo viloyati'), (5, 'Navoiy viloyati'), (6, 'Namangan viloyati'), (7, 'Samarqand viloyati'), (8, 'Surxondaryo viloyati'), (9, 'Sirdaryo viloyati'), (10, 'Toshkent viloyati'), (11, 'Fargʻona viloyati'), (12, 'Xorazm viloyati'), (13, 'Qoraqalpogʻiston Respublikasi')], verbose_name='Yashash Joyi*'),
        ),
    ]
